# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value for this is
# "%(rev)s_%(slug)s_migration_name"
# file_template = %(year)s_%(month).02d_%(day).02d_%(hour).02d%(minute).02d_%(rev)s_%(slug)s

# timezone to use when rendering the date
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# the output encoding used when revision files
# are written from the command line
# output_encoding = utf-8

sqlalchemy.url = postgresql://postgres@localhost:5432/english_teaching

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
